name: Firmware Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
        with:
          version: 0.10.0

      - name: Install STM libs
        run: |
          arduino-cli config init --additional-urls https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json
          arduino-cli config dump
          arduino-cli core update-index
          export STM32DUINO_VERSION="1.9.0"
          arduino-cli core install STM32:stm32@$STM32DUINO_VERSION
          arduino-cli lib install LiquidCrystal@1.0.7
          arduino-cli lib install "Analog Buttons"@1.2.0
          arduino-cli lib install OneButton@1.5.0
          arduino-cli lib install CRC32@2.0.0

      - name: Get the version
        id: version
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Set VERSION variable
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && steps.version.outputs.version != ''
        run: |
          sed -Ei "s/#define VERSION \".+\"/#define VERSION \"${{ steps.version.outputs.version }}\"/" includes/parameters.h

      - name: Build production HW2-FAULHABER
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_PROD/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_FAULHABER/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_FAULHABER/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/respirator.cpp --output output/respirator-production
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-production.bin "dist/respirator-production-HW2-FAULHABER-$VERSION-$GITHUB_SHA.bin"

      - name: Build qualification HW2-FAULHABER
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_QUALIFICATION/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_FAULHABER/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_FAULHABER/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/qualification.cpp --output output/respirator-qualification
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-qualification.bin "dist/respirator-qualification-HW2-FAULHABER-$VERSION-$GITHUB_SHA.bin"

      - name: Build integration test HW2-FAULHABER
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_INTEGRATION_TEST/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_FAULHABER/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_FAULHABER/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/qualification.cpp --output output/respirator-integration-test
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-integration-test.bin "dist/respirator-integration-test-HW2-FAULHABER-$VERSION-$GITHUB_SHA.bin"

      - name: Build production HW2
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_PROD/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/respirator.cpp --output output/respirator-production
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-production.bin "dist/respirator-production-HW2-$VERSION-$GITHUB_SHA.bin"

      - name: Build qualification HW2
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_QUALIFICATION/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/qualification.cpp --output output/respirator-qualification
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-qualification.bin "dist/respirator-qualification-HW2-$VERSION-$GITHUB_SHA.bin"

      - name: Build integration test HW2
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_INTEGRATION_TEST/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/qualification.cpp --output output/respirator-integration-test
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-integration-test.bin "dist/respirator-integration-test-HW2-$VERSION-$GITHUB_SHA.bin"

      - name: Build production HW1
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 1/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_PROD/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/respirator.cpp --output output/respirator-production
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-production.bin "dist/respirator-production-HW1-$VERSION-$GITHUB_SHA.bin"

      - name: Build qualification HW1
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 1/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_QUALIFICATION/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/qualification.cpp --output output/respirator-qualification
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-qualification.bin "dist/respirator-qualification-HW1-$VERSION-$GITHUB_SHA.bin"

      - name: Build integration test HW1
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 1/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_INTEGRATION_TEST/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/qualification.cpp --output output/respirator-integration-test
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-integration-test.bin "dist/respirator-integration-test-HW1-$VERSION-$GITHUB_SHA.bin"

      - name: Build production HW3
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 3/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_PROD/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_FAULHABER/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_FAULHABER/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/respirator.cpp --output output/respirator-production
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-production.bin "dist/respirator-production-HW3-FAULHABER-$VERSION-$GITHUB_SHA.bin"

      - name: Build production HW3 with mass flow meter
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 3/' includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_PROD/' includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_FAULHABER/' includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_FAULHABER/' includes/config.h
          sed -Ei 's/\/\/ #define MASS_FLOW_METER/#define MASS_FLOW_METER/' includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose srcs/respirator.cpp --output output/respirator-production
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' includes/parameters.h)
          cp output/respirator-production.bin "dist/respirator-production-HW3-FAULHABER-MASSFLOWMETER-$VERSION-$GITHUB_SHA.bin"

      - name: Archive binaries
        uses: actions/upload-artifact@v1
        with:
          name: bin
          path: dist/

      - name: Release dev binaries
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          files: |
            dist/*.bin
          body: |
            Auto-release (${{ github.sha }})
            ⚠️ FOR TEST PURPOSE ONLY - DO NOT USE IN PRODUCTION
          tag_name: auto-${{ github.run_id }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release stable binaries
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && steps.version.outputs.version != ''
        with:
          files: |
            dist/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
